### ISSUE TITLE
jQuery dialog migration

### ISSUE THREAD

**Issue by geoidesic** [nakupanda/bootstrap3-dialog#181]
I'm trying to migrate an existing project using jQuery dialog to this library. The problem I have is that, while jQuery dialog simply hides and shows markup that's already on the page, it seems that *this* library forces one to create new markup.

E.g.
```
<div id="jQueryDialog">
  <div id="my_element">
     blah, blah...
  </div>
</div>
```
```
message: $('<div></div>').append($('#jQueryDialog').html());
```
Problems:
1. One ends up with two #my_element id's in the DOM, breaking any related DOM manipulation by ID.
2. If the original jQuery dialog element in the DOM was part of a form, the element generated by *this* library will be outside of the form and thus (for example) submit buttons won't submit.
3. Events that may have been attached to the original elements, will not be copied to the newly created elements, breaking any interactivity.

Is there a way to get this to simply wrap and show an existing element, rather than creating a new one?

**Comment by nakupanda** [comment]
For 1), have a try of message: $('<div></div>').append($('#jQueryDialog').clone()); , but not sure if that will work.

For 2), I think the correct way to represent a form inside a dialog is to put the form inside the dialog, rather than putting the dialog inside the form... have no idea to work this out as the way you wanted.

For 3), try .clone() as well.

Just some quick assumptions, I haven't tried above actually..

**Comment by geoidesic** [comment]
I found a way...

```
  ac.showModal = function (id, title) {
    var msg = $('<div id="bootstrap-dialog"></div>');
    var html = $( "#"+id );
    msg.hide();
    ac.modal =  BootstrapDialog.show({
      model: true,
      title: title,
      message: msg,
      onshown: function () {
        html.appendTo($('#bootstrap-dialog'));
        msg.show();
        html.show();
      },
      onhidden: function () {
        html.hide();
        html.prependTo('body');
      },
      autodestroy: true
    });
  }
```
