### ISSUE TITLE
Add tip about initialize something for remote loaded content with $.load callback

### ISSUE THREAD

**Issue by creadone** [nakupanda/bootstrap3-dialog#299]
I had problem with initialize another jq plugin for loaded content but i solved this with callback.
```javascript
message: $('<div></div>').load('/remote/page', function(){
  // making anything, content is loaded
}),
```
Please add this to documentation for save time another users?

**Comment by baconface** [comment]
I think it is unnecessary to document this. It should be common understanding to ensure the DOM is properly loaded to interact with it further. This is a general principle and I don't think it is this project's place to start teaching things outside of it's scope. This particular instance is also part of the jQuery API and not a bootstrap3-dialog API.

**Comment by baconface** [comment]
Check out my recommendation for loading remote content in issue #305. If that is implemented then it would be reasonable to document it and it would also aid people who in up in your situation.

**Comment by nakupanda** [comment]
The feature loading remote content was removed by intention for better separation in bootstrap3-dialog, from the very beginning.

Long time ago Bootstrap had such a feature but later they removed it, I think that was because of the same reason. 

Actually bootstrap3-dialog has been designed to support loading remote content, but you will have to do more, like @creadone has posted. This inconveniences us a bit on loading remote content, but meantime it provides you more controls on it. 

Take a look at this issue, https://github.com/nakupanda/bootstrap3-dialog/issues/293, if necessary, you can create your own tool for easier loading remote page, or even adding animation for the loading process, this explains my statements about why I decided to not support such an option for loading remote page.

However, I will carefully look into @baconface idea, if it doesn't break any flexibility of bootstrap3-dialog, we have no reason to refuse it.

Thank guys.

**Comment by nakupanda** [comment]
Oh sorry, I should answer the question first.

Yes we should put this into the docs, actually our documentations has been out of date.. gotta make fresh sometime.

**Comment by nakupanda** [comment]
Also, feel free to create awesome examples in document page.

**Comment by creadone** [comment]
@nakupanda, @baconface, thank guys!
